name: nox
on: [push]
jobs:
  nox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: excitedleigh/setup-nox@v2.0.0
      - run: pip install nox-poetry
      - run: nox
