name: Tests

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        # TODO: Add windows-latest
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9"]

    defaults:
      run:
        shell: bash

    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      # - name: Get full Python version
      #   id: full-python-version
      #   run: echo ::set-output name=version::$(python3 -c "import sys; print('-'.join(str(v) for v in sys.version_info))")

      - uses: actions/cache@v2
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      # - name: Ensure cache is healthy
      #   if: steps.cache.outputs.cache-hit == 'true'
      #   run: timeout 10s poetry run pip --version || rm -rf .venv
      # - name: Install dependencies
      #   run: poetry install
